### ISSUE TITLE
References 

### ISSUE THREAD

**Issue by MVitalina** [firefly114/euro_lab1#2]
It can be dangerous to save references for neighbours.
Try to rewrite it in next way: each city just can give and collect coins, but it can`t sent coins to other cities
https://github.com/firefly114/euro_lab1/blob/ddcf80367f2d2bafb3a211a3b931031eef297489/src/city.js#L39

**Comment by firefly114** [comment]
it doesn't send them to another city. Income is an internal field of City class. The method only modifies it and then at the end of the day, clears.
