### ISSUE TITLE
Function call

### ISSUE THREAD

**Issue by IanaKhitsko** [firefly114/euro_lab1#8]
https://github.com/firefly114/euro_lab1/blob/2a2b1058a26f86c03e6977a217d1c0f487201020/src/index.js#L31

I'm not js dev, please explain how does it work? Who calls this function? And why is it unnamed?

**Comment by firefly114** [comment]
This is the main function to run program, because it is running just in place it is not required to have a name. My bad that I put it here, it is not required to have a function here, so I removed it left a code it contained just in file.
Resolved
